spring:
  datasource:
    url: jdbc:mysql://${MY_HOST:localhost}:${MY_PORT:5431}/${DB_NAME:carRental}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:123456}
  jpa:
    generate-ddl: true
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
server:
  servlet:
    context-path: /api
